package com.jerry.http_client_util;

import com.jerry.http_client_util.utility.HttpClientUtil;
import org.apache.http.HttpHeaders;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpDelete;
import org.apache.http.client.methods.HttpPost;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.HashMap;
import java.util.Map;

@RunWith(SpringRunner.class)
@SpringBootTest
public class HttpClientUtilApplicationTests {

	@Test
	public void contextLoads() {
	}

	@Test
	public void fileUpLoadTest(){

		String uri = "http://146.122.219.108:9002/testUploadFile";
		HttpPost httpPost = new HttpPost(uri);
		CloseableHttpResponse chResponse = HttpClientUtil.sendHttpsPostWithFile(httpPost, "C:\\Users\\x1twbm\\Desktop\\owl\\wine.owl");

		String response = HttpClientUtil.getResponseEntity(chResponse);

		System.out.println("code:" + HttpClientUtil.getResponseCode(chResponse));
	}

	@Test
	public void postFormTest(){

		String uri = "http://146.122.219.56:8080/login";
		Map<String, Object> map = new HashMap<>();
		map.put("username", "zhang xiao");
		map.put("password", "hahah");
		CloseableHttpResponse closeableHttpResponse = HttpClientUtil.sendHttpPostWithForm(uri, map);

		System.out.println("code:" + HttpClientUtil.getResponseCode(closeableHttpResponse));
		System.out.println("content:" + HttpClientUtil.getResponseEntity(closeableHttpResponse));
	}

	@Test
	public void msDeleteAsset() {

		String token = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1OTI2NTE1ZDhhNGM0NjBhYWQ3NjY0ZWYzZTk5NTEzNSIsImV4dF9hdHRyIjp7ImVuaGFuY2VyIjoiWFNVQUEifSwic3ViIjoiNGRjODAyY2ItYThhMi00NDA5LTk1YTEtYjA1ZmUxZDNmMjE3Iiwic2NvcGUiOlsiVGltZVNlcmllc01vbml0b3IuUmVhZCIsInRtLnQyLnIiLCJhc3IuciIsInRtLnQyLnciLCJhYXMuYyIsImJwLnBkIiwidGhpbmcuY29uZi5yIiwiYXV0aC5vZ2EuYyIsImF1dGgub2dhLmQiLCJTQU0uUmVhZCIsIlVzZXJNZ210Lk1vZGlmeVVzZXIiLCJ0aGluZy5FdmVudC51IiwibG9jLmMiLCJsb2MuZCIsIkNvbW1TcnYuc20iLCJtY2FtLmMiLCJjb25mLnIiLCJtY2FtLmQiLCJFbmdpbmVlcmluZy5WaWV3T3JkZXJpbmciLCJjdC5yIiwib2ViLnIiLCJ1bS5tdSIsImFhcy51IiwidHNjLmMiLCJFbmdpbmVlcmluZy5WaWV3QXNzZXRDb25maWciLCJjb25mLmQiLCJmaWxlLmRhIiwiY29uZi5jIiwib3BlbmlkIiwiVXNlck1nbXQuVmlld0VuZGN1c3RvbWVyIiwidGRlLnIiLCJtYy5yIiwiQ29tbVNydi5hYyIsImdlb2NvZGVyLlF1ZXJ5IiwiYXNtLnIiLCJBcHBNZ210LnNtIiwieHNfYXV0aG9yaXphdGlvbi5yZWFkIiwidGRlLmNvbmYuciIsImRyLnciLCJ0ZGUuZCIsIkVuZ2luZWVyaW5nLkRlbGV0ZUFzc2V0IiwidGRlLmMiLCJ0aGluZy5jb25mLmMiLCJhc20uYyIsImRyLnIiLCJhc20uZCIsIkFwcE1nbXQuc3MiLCJFbmdpbmVlcmluZy5Nb2RpZnlEYXRhU291cmNlIiwidGhpbmcuY29uZi5kIiwiZGZzLnNtIiwidGRlLmNvbmYuZCIsInRkZS5jb25mLmMiLCJFbmdpbmVlcmluZy5Nb2RpZnlMb2NhdGlvbiIsImFzbS51IiwidHNjLnIiLCJ0c2MudSIsIkVuZ2luZWVyaW5nLk1vZGlmeU5ldHdvcmsiLCJhZm0uZCIsIkVuZ2luZWVyaW5nLk9uYm9hcmRBZ2VudCIsImFmbS5jIiwiZXB1LmMiLCJsb2MuciIsImxvYy51IiwiZmgudyIsIm1jYW0uciIsIm1jYW0udSIsImZoLnIiLCJhZm0udSIsIkVuZ2luZWVyaW5nLk1vZGlmeUJveEluZm9ybWF0aW9uIiwiYWZtLnIiLCJlcHUuciIsInVtLnZ1IiwiZmlsZS5jIiwiZmlsZS5kIiwiRW5naW5lZXJpbmcuQ3JlYXRlQXNzZXQiLCJ0ZW5hbnQucGVycy5yIiwiZW0udSIsImF1dGguciIsInRzLmMiLCJhdXRoLnUiLCJlbS5yIiwidW0udmVjIiwidHMuZCIsImFwcGducnRyLmMiLCJmaWxlLnIiLCJ0ZW5hbnQub3JnLmQiLCJ0ZW5hbnQudGVuYW50LnIiLCJkZnMucmFzIiwiRW5naW5lZXJpbmcuTW9kaWZ5RGF0YU1hcHBpbmciLCJtY2MucmEiLCJtY2VtLmMiLCJ1dHMucmMiLCJFbmdpbmVlcmluZy5Nb2RpZnlBc3BlY3QiLCJtY2FzLmMiLCJFbmdpbmVlcmluZy5HZW5lcmF0ZUZpbGUiLCJtY2FzLmQiLCJTQVRTTWFwcGVyLlJlYWQiLCJkc3RwLnIiLCJzYWJzLnIiLCJ0aGluZy5kIiwidGhpbmcuYyIsIlVzZXJNZ210LlZpZXdVc2VyIiwic2Ficy53IiwiRW5naW5lZXJpbmcuTW9kaWZ5T3JkZXJpbmciLCJkc3RwLmQiLCJkc3RwLmMiLCJ1YWEudXNlciIsImF1dGguYyIsImVtLmMiLCJhdXRoLmQiLCJ0aGluZy5yIiwiam0uciIsImFwcGducnRyLnIiLCJVc2VyTWdtdC5Nb2RpZnlFbmRjdXN0b21lciIsIkVuZ2luZWVyaW5nLk1vZGlmeURhdGFQb2ludCIsImptLnciLCJkc3RwLnUiLCJ0ZW5hbnQub3JnLnIiLCJhcHBtZ3IuciIsInBpbS5yIiwiYXJlLmMiLCJhcmUuZCIsInVtLm1lYyIsIlRpbWVTZXJpZXNNb25pdG9yLldyaXRlIiwiU0FNLldyaXRlIiwiRW5naW5lZXJpbmcuVmlld0N1c3RvbWVySW5mb3JtYXRpb24iLCJhcmUuciIsInVsLnciLCJhcmUudSIsIndzLnIiLCJhcHBtZ3IuYyIsImJwLnRlbmFudC5yIiwibWNjLmRhIiwiYXJlLnJzIiwibWNlbS5yIiwidGhpbmcuRXZlbnQuZCIsImRmcy5hbXIiLCJlbS5ldC5kIiwiZW0uZXQuYyIsImFzbS5oLnIiLCJicC5kIiwidWwuciIsIm1jYXMuciIsImJwLmMiLCJhc20uaC53IiwibWNhcy51IiwidGhpbmcuRXZlbnQuciIsImFvZC5yIiwiYXNtLm12IiwiZW0uZXQudSIsImF1dGgub2dhLnIiLCJmcHUuYyIsImZwdS5kIiwiZW0uZXQuciIsInRzLnIiLCJicC51IiwiRW5naW5lZXJpbmcuTW9kaWZ5Q3VzdG9tZXJJbmZvcm1hdGlvbiIsImFzbS5oLmQiLCJhdXRoLm9nYS51IiwiYnAuciIsImZwdS5yIiwibWNjLmNhIiwidGhpbmcuRXZlbnQuYyJdLCJjbGllbnRfaWQiOiJzYi1BcHBSb3V0ZXIiLCJjaWQiOiJzYi1BcHBSb3V0ZXIiLCJhenAiOiJzYi1BcHBSb3V0ZXIiLCJncmFudF90eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwidXNlcl9pZCI6IjRkYzgwMmNiLWE4YTItNDQwOS05NWExLWIwNWZlMWQzZjIxNyIsIm9yaWdpbiI6InVzZXJpZHAiLCJ1c2VyX25hbWUiOiJob25nLm11QHNpZW1lbnMuY29tIiwiZW1haWwiOiJob25nLm11QHNpZW1lbnMuY29tIiwiZ2l2ZW5fbmFtZSI6ImhvbmcubXUiLCJmYW1pbHlfbmFtZSI6InNpZW1lbnMuY29tIiwiYXV0aF90aW1lIjoxNTEwNzk2MDEzLCJyZXZfc2lnIjoiY2U2MjBhMzgiLCJpYXQiOjE1MTA3OTYwMTUsImV4cCI6MTUxMDgzOTIxNSwiaXNzIjoiaHR0cDovL3NhZy1jdGNoaS5sb2NhbGhvc3Q6ODA4MC91YWEvb2F1dGgvdG9rZW4iLCJ6aWQiOiJzYWctY3RjaGkiLCJ4cy51c2VyLmF0dHJpYnV0ZXMiOnt9LCJ4cy5zeXN0ZW0uYXR0cmlidXRlcyI6eyJ4cy5zYW1sLmdyb3VwcyI6WyJPRU1BZG1pblVzZXIiXSwieHMucm9sZWNvbGxlY3Rpb25zIjpbIk9FTUFkbWluVXNlciJdfSwiYXVkIjpbIkFwcE1nbXQiLCJhc3IiLCJicC50ZW5hbnQiLCJhdXRoIiwiY29uZiIsImdlb2NvZGVyIiwic2ItQXBwUm91dGVyIiwibWNjIiwibWNlbSIsImF1dGgub2dhIiwiZHIiLCJ0aGluZy5FdmVudCIsInBpbSIsIm1jIiwidWwiLCJ1bSIsInhzX2F1dGhvcml6YXRpb24iLCJhcHBnbnJ0ciIsIm9wZW5pZCIsImVtIiwic2FicyIsImVwdSIsImRmcyIsImFwcG1nciIsInV0cyIsIlVzZXJNZ210IiwiYXNtLmgiLCJTQU0iLCJsb2MiLCJmaCIsImptIiwidHNjIiwiU0FUU01hcHBlciIsInRtLnQyIiwidGVuYW50LnBlcnMiLCJvZWIiLCJicCIsIkVuZ2luZWVyaW5nIiwiYWFzIiwiZmlsZSIsInRlbmFudC5vcmciLCJ1YWEiLCJhcmUiLCJ3cyIsIlRpbWVTZXJpZXNNb25pdG9yIiwiZHN0cCIsImFmbSIsImZwdSIsIm1jYW0iLCJjdCIsInRoaW5nLmNvbmYiLCJ0ZGUiLCJlbS5ldCIsIkNvbW1TcnYiLCJhb2QiLCJhc20iLCJ0ZGUuY29uZiIsIm1jYXMiLCJ0aGluZyIsInRzIiwidGVuYW50LnRlbmFudCJdfQ.QO2W_pP67tB54lMU8NKaEkWbcjK6jvZcst-dBFCoQ8uSH8LYfaGhIdt_5ylknO7_cI0CjOtzlTalJ697cFfTlF7XHr2ZspTz6qesT_p6ZPlHw6CwKiJt7Z0zaNkAjdn_eaT27kFJ1vHX1Ram8xeXUCrkEDcKOwZqOMavEOne-Yz8ES28w3ACRxA-BQyXLRcFPltOhOdf3HIVDiNl-WbBeyoB4raDkjmeJEWF8kxNq3MT3hNRllz9L2MYUOVetbX0wXeCULpqagqGd3rluAsLgSiEMoyrHrEdu9MvbBauliEUpn5HoaCUP0D2AbZwvLlByjH01vqlAP5O3AVKfmCI_EJdnGxL4eU30AU1sfrU5uOuiX5EdbWf3TeOvbGkksNpUzOMEpKJF76Hipftj2PNxHcTs-DuhArfYiyIITLg24sNfXS4eiL7r75xqlBF7qFHXbz-vrWLPwAE06QMy5SsqEDPYKvHGUB8aQvDXKkDJkgmBBOj40TmQpIMj1DznnnbWaWVXdU6LJqTlbMHse4Ug7lk742LG4P9YRc8RFB94t0qi7l2KNMviy9Q2xYn9Ut7hjj-2HvJnbedYH6C6SSrJtTlWP_thBT5i0pUDt8UylDp2QuzJAK53ye3ZyVYcpmRkjn70bBakrHs40e_XjNBmQ9fC-r8zBexPXFPl3gK8MY";
		String uri = "https://mindgate.appsdev.mindsphere.io/api/assetmanagement/api/assets/3F5CD3CA6EB54B8A951F9A75E3F5B025";
		HttpDelete httpsDelete = new HttpDelete(uri);
		httpsDelete.addHeader(HttpHeaders.AUTHORIZATION, token);
		CloseableHttpResponse response = HttpClientUtil.sendHttpsDelete(httpsDelete);
		System.out.println("code:" + HttpClientUtil.getResponseCode(response));
		System.out.println("content:" + HttpClientUtil.getResponseEntity(response));
	}
}
